package io.autumn.twilight.creativemodetab

import io.autumn.torchberry.annotations.OnInitialize
import io.autumn.twilight.Twilight
import io.autumn.twilight.block.TwilightBlocks
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab
import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.core.registries.Registries
import net.minecraft.network.chat.Component
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.CreativeModeTab
import net.minecraft.world.item.ItemStack

object TwilightCreativeModeTabs {

    val DEV_TAB: ResourceKey<CreativeModeTab> = ResourceKey.create(Registries.CREATIVE_MODE_TAB, Twilight.namespaceAndPath("dev_tab"))

    fun registerCreativeModeTabs() {
        Registry.register(
            BuiltInRegistries.CREATIVE_MODE_TAB,
            DEV_TAB,
            FabricCreativeModeTab.builder()
                .title(Component.literal("Development"))
                .icon { ItemStack(TwilightBlocks.TWILIGHT_OAK_SET.log) }
                .displayItems { _, entries ->
                    entries.accept(TwilightBlocks.CORONATION_CARPET_CRUDE)
                    entries.accept(TwilightBlocks.HEDGE)
                    entries.accept(TwilightBlocks.ROOT_BLOCK)
                    entries.accept(TwilightBlocks.LIVEROOT_BLOCK)
                    entries.accept(TwilightBlocks.FIDDLEHEAD)
                    entries.accept(TwilightBlocks.MUSHGLOOM)
                    entries.accept(TwilightBlocks.MAYAPPLE)
                    entries.accept(TwilightBlocks.FIREFLY)

                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.log)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.strippedLog)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.wood)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.strippedWood)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.leaves)
                    entries.accept(TwilightBlocks.RAINBOW_OAK_LEAVES)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.sapling)
                    entries.accept(TwilightBlocks.RAINBOW_OAK_SAPLING)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.planks)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.door)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.trapdoor)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.fence)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.fenceGate)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.stairs)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.slab)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.button)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.pressurePlate)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.signItem)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.TWILIGHT_OAK_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_TWILIGHT_OAK_CHEST)

                    entries.accept(TwilightBlocks.CANOPY_SET.log)
                    entries.accept(TwilightBlocks.CANOPY_SET.strippedLog)
                    entries.accept(TwilightBlocks.CANOPY_SET.wood)
                    entries.accept(TwilightBlocks.CANOPY_SET.strippedWood)
                    entries.accept(TwilightBlocks.CANOPY_SET.leaves)
                    entries.accept(TwilightBlocks.CANOPY_SET.sapling)
                    entries.accept(TwilightBlocks.CANOPY_SET.planks)
                    entries.accept(TwilightBlocks.CANOPY_SET.door)
                    entries.accept(TwilightBlocks.CANOPY_SET.trapdoor)
                    entries.accept(TwilightBlocks.CANOPY_SET.fence)
                    entries.accept(TwilightBlocks.CANOPY_SET.fenceGate)
                    entries.accept(TwilightBlocks.CANOPY_SET.stairs)
                    entries.accept(TwilightBlocks.CANOPY_SET.slab)
                    entries.accept(TwilightBlocks.CANOPY_SET.button)
                    entries.accept(TwilightBlocks.CANOPY_SET.pressurePlate)
                    entries.accept(TwilightBlocks.CANOPY_SET.signItem)
                    entries.accept(TwilightBlocks.CANOPY_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.CANOPY_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_CANOPY_CHEST)

                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.log)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.strippedLog)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.wood)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.strippedWood)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.leaves)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.sapling)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.planks)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.door)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.trapdoor)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.fence)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.fenceGate)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.stairs)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.slab)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.button)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.pressurePlate)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.signItem)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_ROOT)
                    entries.accept(TwilightBlocks.TWILIGHT_MANGROVE_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_TWILIGHT_MANGROVE_CHEST)

                    entries.accept(TwilightBlocks.DARKWOOD_SET.log)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.strippedLog)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.wood)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.strippedWood)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.leaves)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.sapling)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.planks)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.door)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.trapdoor)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.fence)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.fenceGate)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.stairs)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.slab)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.button)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.pressurePlate)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.signItem)
                    entries.accept(TwilightBlocks.DARKWOOD_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.DARKWOOD_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_DARKWOOD_CHEST)

                    entries.accept(TwilightBlocks.TIMEWOOD_SET.log)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.strippedLog)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.wood)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.strippedWood)
                    entries.accept(TwilightBlocks.TIMEWOOD_CORE)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.leaves)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.sapling)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.planks)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.door)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.trapdoor)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.fence)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.fenceGate)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.stairs)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.slab)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.button)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.pressurePlate)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.signItem)
                    entries.accept(TwilightBlocks.TIMEWOOD_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.TIMEWOOD_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_TIMEWOOD_CHEST)

                    entries.accept(TwilightBlocks.TRANSWOOD_SET.log)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.strippedLog)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.wood)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.strippedWood)
                    entries.accept(TwilightBlocks.TRANSWOOD_CORE)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.leaves)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.sapling)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.planks)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.door)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.trapdoor)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.fence)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.fenceGate)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.stairs)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.slab)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.button)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.pressurePlate)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.signItem)
                    entries.accept(TwilightBlocks.TRANSWOOD_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.TRANSWOOD_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_TRANSWOOD_CHEST)

                    entries.accept(TwilightBlocks.MINEWOOD_SET.log)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.strippedLog)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.wood)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.strippedWood)
                    entries.accept(TwilightBlocks.MINEWOOD_CORE)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.leaves)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.sapling)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.planks)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.door)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.trapdoor)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.fence)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.fenceGate)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.stairs)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.slab)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.button)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.pressurePlate)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.signItem)
                    entries.accept(TwilightBlocks.MINEWOOD_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.MINEWOOD_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_MINEWOOD_CHEST)

                    entries.accept(TwilightBlocks.SORTWOOD_SET.log)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.strippedLog)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.wood)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.strippedWood)
                    entries.accept(TwilightBlocks.SORTWOOD_CORE)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.leaves)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.sapling)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.planks)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.door)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.trapdoor)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.fence)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.fenceGate)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.stairs)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.slab)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.button)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.pressurePlate)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.signItem)
                    entries.accept(TwilightBlocks.SORTWOOD_SET.hangingSignItem)
                    entries.accept(TwilightBlocks.SORTWOOD_CHEST)
                    entries.accept(TwilightBlocks.TRAPPED_SORTWOOD_CHEST)
                }
                .build()
        )
    }

    @OnInitialize
    fun initialize() {
        Twilight.LOGGER?.info("Registering creative mode tabs for ${Twilight.NAMESPACE}.")
        registerCreativeModeTabs()
    }
}